Date: Thu, 1 Jun 2017 13:24:51 -0700 (PDT)
From: =?UTF-8?Q?Guillaume_DOLL=C3=89?= <dolle.g...@gmail.com>
To: singularity <singu...@lbl.gov>
Message-Id: <d561f36e-3187-4bdf-ac27-bd29327253cc@lbl.gov>
Subject: Private repo dockerhub auth bug ?
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_157_913687885.1496348691062"

------=_Part_157_913687885.1496348691062
Content-Type: multipart/alternative; 
	boundary="----=_Part_158_2273924.1496348691062"

------=_Part_158_2273924.1496348691062
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

Hi all

I've a problem with auth and dockerhub, when I try to bootstrap (`sudo 
singularity bootstrap myimage Singularity`) a private dockerhub repository.
I follow the documentation here 
http://singularity.lbl.gov/docs-docker#authentication-in-the-singularity-build-file

I tried to both method (with export (+bashrc +/etc/profle) and with 
specfile username,password) but I always get this debug output

```
VERBOSE2 SINGULARITY_DOCKER_USERNAME not defined (None)
VERBOSE2 SINGULARITY_DOCKER_PASSWORD found
...

ERROR Improperly formed manifest, layers or fsLayers must be present
```

If I test directly with

```

CREDENTIAL=$(echo -n vanessa:[password] | base64)TOKEN=$(http 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:vanessa/code-samples:pull' Authorization:"Basic $CREDENTIAL" | jq -r '.token')
http https://index.docker.io/v2/vanessa/code-samples/tags/list Authorization:"Bearer $TOKEN"

```

It works, I get OK status.

I guess there's there's something odd with my python `get.environ` on my 
system (archlinux/ python 3.6.1).
When I try to print the output of username in libexec/default.py 
os.environ.get(), the values are always None.

Have someone any idea ? Or can confirm this problem ?




------=_Part_158_2273924.1496348691062
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hi all<br><br>I&#39;ve a problem with auth and dockerhub, =
when I try to bootstrap (`<span style=3D"color: rgb(204, 0, 0);">sudo singu=
larity bootstrap myimage Singularity</span>`) a private dockerhub repositor=
y.<br>I follow the documentation here <a href=3D"http://singularity.lbl.gov=
/docs-docker#authentication-in-the-singularity-build-file">http://singulari=
ty.lbl.gov/docs-docker#authentication-in-the-singularity-build-file</a><br>=
<br>I tried to both method (with export (+bashrc +/etc/profle) and with spe=
cfile username,password) but I always get this debug output<br><br>```<br><=
span style=3D"color: rgb(61, 133, 198);">VERBOSE2 SINGULARITY_DOCKER_USERNA=
ME not defined (None)<br>VERBOSE2 SINGULARITY_DOCKER_PASSWORD found</span><=
br><span style=3D"color: rgb(61, 133, 198);">...<br><br>ERROR Improperly fo=
rmed manifest, layers or fsLayers must be present</span><br>```<br><br>If I=
 test directly with<br><br>```<br><div class=3D"language-bash highlighter-r=
ouge"><pre class=3D"highlight"><span style=3D"color: rgb(61, 133, 198);"><c=
ode><span class=3D"nv">CREDENTIAL</span><span class=3D"o">=3D</span><span c=
lass=3D"k">$(</span><span class=3D"nb">echo</span> -n vanessa:[password] | =
base64<span class=3D"k">)</span>
<span class=3D"nv">TOKEN</span><span class=3D"o">=3D</span><span class=3D"k=
">$(</span>http <span class=3D"s1">&#39;https://auth.docker.io/token?servic=
e=3Dregistry.docker.io&amp;scope=3Drepository:vanessa/code-samples:pull&#39=
;</span> Authorization:<span class=3D"s2">&quot;Basic </span><span class=3D=
"nv">$CREDENTIAL</span><span class=3D"s2">&quot;</span> | jq -r <span class=
=3D"s1">&#39;.token&#39;</span><span class=3D"k">)</span><br></code></span>=
<code><span style=3D"color: rgb(61, 133, 198);"><code>http https://index.do=
cker.io/v2/vanessa/code-samples/tags/list Authorization:<span class=3D"s2">=
&quot;Bearer </span><span class=3D"nv">$TOKEN</span><span class=3D"s2">&quo=
t;</span></code></span>
</code></pre>
</div>```<br><br>It works, I get OK status.<br><br>I guess there&#39;s ther=
e&#39;s something odd with my python `get.environ` on my system (archlinux/=
 python 3.6.1).<br>When I try to print the output of username in libexec/de=
fault.py os.environ.get(), the values are always None.<br><br>Have someone =
any idea ? Or can confirm this problem ?<br><br><br><br></div>
------=_Part_158_2273924.1496348691062--

------=_Part_157_913687885.1496348691062--
