Date: Thu, 27 Oct 2016 11:37:24 -0700 (PDT)
From: =?UTF-8?Q?Stack_Koror=C4=81?= <i.am...@gmail.com>
To: singularity <singu...@lbl.gov>
Message-Id: <1a3eb053-d0f4-457c-82ca-93ecf95017ac@lbl.gov>
In-Reply-To: <a04fb903-f624-442c-897d-217374de965d@lbl.gov>
References: <CAMfmYegA2BbQ6V-ZmUDRgm35GSoBXiMh82K7bAhZLvynGce7Cw@mail.gmail.com>
 <CAMfmYeg=OkyMa5_b5K30==3ww_sS1ONeA7oaNO-gU8B=yRnmUg@mail.gmail.com>
 <68d76dc9-db97-406a-acc8-41fa057d2cbe@lbl.gov>
 <6EC1A210-1B0D-482C-A1D4-95B08047D3CD@gmail.com>
 <a4e01874-db59-43fa-8c26-7dcbe41c2264@lbl.gov>
 <CAM=pu+JvEF_qGwb1ELw7E1sTsAz6skmGmZ7DB8A6LWQsT5NZiQ@mail.gmail.com>
 <404f9dca-6150-4719-be05-b6024e037d19@lbl.gov>
 <f0e683cc-7b0e-4dba-ae18-95b5412924f8@lbl.gov>
 <b1c90da8-ab38-49c6-8299-cbc1495d6b5f@lbl.gov>
 <22628e17-7749-435b-a41d-b2c19b18cc99@lbl.gov>
 <20161027164312.GA23918@sillage.bis.pasteur.fr>
 <a04fb903-f624-442c-897d-217374de965d@lbl.gov>
Subject: Re: [Singularity] How to use GPU in singularity?
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_170_192488852.1477593444956"

------=_Part_170_192488852.1477593444956
Content-Type: multipart/alternative; 
	boundary="----=_Part_171_1964634735.1477593444956"

------=_Part_171_1964634735.1477593444956
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

Editing /singularity inside the container is letting me run events 
(including setting up the environment). 

However, I am not getting it to pass the file along per the documentation 
here: http://singularity.lbl.gov/docs-run


exec /usr/bin/python3 "%@"

/usr/bin/python3: can't open file '%@': [Errno 2] No such file or directory

But I am getting closer!

------=_Part_171_1964634735.1477593444956
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<div dir="ltr">Editing /singularity inside the container is letting me run events (including setting up the environment). <br><br>However, I am not getting it to pass the file along per the documentation here: http://singularity.lbl.gov/docs-run<br><br><br>exec /usr/bin/python3 <code class="highlighter-rouge">&quot;%@&quot;<br><br>/usr/bin/python3: can&#39;t open file &#39;%@&#39;: [Errno 2] No such file or directory<br><br></code>But I am getting closer!<br></div>
------=_Part_171_1964634735.1477593444956--

------=_Part_170_192488852.1477593444956--
