X-Received: by 10.129.62.15 with SMTP id l15mr17093228ywa.110.1495664121598;
        Wed, 24 May 2017 15:15:21 -0700 (PDT)
X-BeenThere: singularity@lbl.gov
Received: by 10.107.11.211 with SMTP id 80ls2734687iol.33.gmail; Wed, 24 May
 2017 15:15:21 -0700 (PDT)
X-Received: by 10.98.204.130 with SMTP id j2mr41162867pfk.107.1495664120862;
        Wed, 24 May 2017 15:15:20 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1495664120; cv=none;
        d=google.com; s=arc-20160816;
        b=0xW4QlnfAczdaF67Vx9Gq/tDqp8KBbidmKDbRgcMept3jp6Ma0RnCj0VPqQ9Hsmdpv
         +6x5Vu3k4c1wFjJtCPfQwMRpwaY3DBdSSTNUK3KW+E3M7IRoi9DD/PtUpc2qdtaB7Who
         VqVrl4HrFIamEIqrul5Zg0rMNMtasHgx/6QI7ULmfxDQ4GBi6X3+ny6F+EA1ZGw7xgZO
         j6l7pfxCqqs5O4jVJtYZpCw/hKxcBP5lr8RcSvRVYaAuL3SGHFsOTgCpy9mlQWbfCu9i
         voAC3Uorw3i9uNwUZTi0RpsAJGNp3YgPSqLW8Nh4SFj4DaxIlsWVPStkrXbOY8wzGFMd
         2d0A==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=to:subject:message-id:date:from:references:in-reply-to:mime-version
         :dkim-signature:arc-authentication-results;
        bh=Jq8ncwTHo/latnPfz/cJyE6A3LeLn68yDfGtneSmUxM=;
        b=t5KPKW4s07LfZFcLZcKKupSIS9cvU3OnEUWhUaizXtkc+Z/4CCC94rDUuFI2N7YX2T
         BwCHqXk6FOmWKL5vP7TIySBrUyPHeXNFsKswXojCgX5PeYTY0Kn82AGlZNv4CG7Va4oe
         ZpNUYnGyeOFKtCPWSmPmLCl/nDhEeRVouBlKTkOVeP62/LrJ6y0/4DhDOtg3Ah0PttFu
         JsWFLG3MZ7hvrWkRZTyRZd1aNzquEzm/zedUhFBdUDLDqBHBCwczJZ95izJ32sW+tzw/
         SHU5GsisAJs7vfFpkoAtXGxaZy2QRSJ/tuLzJ54uRkKWWTrUg+J0m88dQIYZ9d03rY7G
         MxGQ==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass head...@gmail.com;
       spf=pass (google.com: domain of jerrin...@gmail.com designates 209.85.218.51 as permitted sender) smtp.mailfrom=jerrin...@gmail.com
Return-Path: <jerrin...@gmail.com>
Received: from fe4.lbl.gov (fe4.lbl.gov. [128.3.41.71])
        by mx.google.com with ESMTP id m19si24767037pgk.121.2017.05.24.15.15.20
        for <singu...@lbl.gov>;
        Wed, 24 May 2017 15:15:20 -0700 (PDT)
Received-SPF: pass (google.com: domain of jerrin...@gmail.com designates 209.85.218.51 as permitted sender) client-ip=209.85.218.51;
Authentication-Results: mx.google.com;
       dkim=pass head...@gmail.com;
       spf=pass (google.com: domain of jerrin...@gmail.com designates 209.85.218.51 as permitted sender) smtp.mailfrom=jerrin...@gmail.com
X-Ironport-SBRS: 2.7
X-IronPort-Anti-Spam-Filtered: true
X-IronPort-Anti-Spam-Result: =?us-ascii?q?A2HoBwBeBSZZfzPaVdFcHAEBBAEBCgEBF?=
 =?us-ascii?q?wEBBAEBCgEBgwFMAT6BDAeDaIE2o1SHKYcEQySBd4QJAoJsB0MUAQEBAQEBAQE?=
 =?us-ascii?q?BAQECEAEBCQsLCCYxgjMiEEYpLgEBAQEBAQEBAQEBHwIrBDwDAyMdARseAwwGB?=
 =?us-ascii?q?QQHNwICIgERAQUBHIhvgTcBAxUFoU4/jAeCBAUBHIMKBYNbChknDVaDKgEBAQE?=
 =?us-ascii?q?BBQEBAQEBARoCBhKGTYRGNIROgyiCYAEEniOHIIwIkXeQHIJqFB+BFTaBLC8gI?=
 =?us-ascii?q?nSETw8cgX8kNolCAQEB?=
X-IronPort-AV: E=Sophos;i="5.38,388,1491289200"; 
   d="scan'208,217";a="75627011"
Received: from mail-oi0-f51.google.com ([209.85.218.51])
  by fe4.lbl.gov with ESMTP; 24 May 2017 15:15:18 -0700
Received: by mail-oi0-f51.google.com with SMTP id w10so260438059oif.0
        for <singu...@lbl.gov>; Wed, 24 May 2017 15:15:18 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:in-reply-to:references:from:date:message-id:subject:to;
        bh=Jq8ncwTHo/latnPfz/cJyE6A3LeLn68yDfGtneSmUxM=;
        b=NncUURDFUwEyLSpDpo2EFrmIE4KQ4hxNT501gp8uvV1hWsw/5qRyyr0Vqa2jCphG64
         pI/RZ3m+ZD21hXJdA8AkH58cKqoFsd2DKDRAjdigmXvAEcTJnScIMOq5sPQUr5YfzUrJ
         gL6oseDCiAv6rvtUEjpj7Ev2MWjX4sg6p96/Kd9fyoA8zX8jTD2oHGRK6QjynjJDCTx1
         jrh8RD42WLnxBCkb5TuyiRSldmbUwVUOC18h51Xp776GAy4dsDm+J9cXliCSUXVt8TXf
         8BAO0UmGnPypyC9bP9tLTW5bQ81IDxoNEORKHtPyxbIKuJXSSlzU3S9XB2boZSAMMU3c
         9ScQ==
X-Gm-Message-State: AODbwcDKytNDXH3dCRaX+26EApfb5pmwxyKpz1ZUEcowxJgIs60lfAjn
	W3V7ApNeNl7f2rmROMCFrDT9Qc0TYUoWSKA=
X-Received: by 10.202.206.193 with SMTP id e184mr18013145oig.91.1495664117879;
 Wed, 24 May 2017 15:15:17 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.157.17.106 with HTTP; Wed, 24 May 2017 15:14:57 -0700 (PDT)
In-Reply-To: <CAM=pu+JjS6G951+zb_OUaHizwjACjciWc-jz4yNjr6b-N6iZXg@mail.gmail.com>
References: <CA+KhMPsyKRrwZNrH_eeZpLZ-EXRdHfKMzdpUFj--g14gUUxAqg@mail.gmail.com>
 <CAM=pu+JjS6G951+zb_OUaHizwjACjciWc-jz4yNjr6b-N6iZXg@mail.gmail.com>
From: Jerrin Suresh <jerrin...@gmail.com>
Date: Wed, 24 May 2017 18:14:57 -0400
Message-ID: <CA+KhMPsP6xbq2Rx2AOLSkUuXbwkcq1eaC=D_PrBApa0iNNtR9A@mail.gmail.com>
Subject: Re: [Singularity] Conflicting modules b/w container and host
To: singularity@lbl.gov
Content-Type: multipart/alternative; boundary="001a113d2e7273191705504c708f"

--001a113d2e7273191705504c708f
Content-Type: text/plain; charset="UTF-8"

I don't think the first option works for us as we have some bind points and
the container ignores them in the --contain switch. The --cleanenv is also
not available in the server version of singularity and my guess is would
result in something similar.

I did not understand the second option.

The third option is the funny part, copied below is the result.

~~~~
Singularity.tensorflow.img> which python
/N/soft/cle4/python/2.7.8/bin/python
Singularity.tensorflow.img> python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Could not open PYTHONSTARTUP
IOError: [Errno 2] No such file or directory: '/etc/pythonstart'
>>> import numpy
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File
"/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/__init__.py",
line 180, in <module>
from . import add_newdocs
File
"/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/add_newdocs.py",
line 13, in <module>
from numpy.lib import add_newdoc
File
"/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/lib/__init__.py",
line 8, in <module>
from .type_check import *
File
"/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/lib/type_check.py",
line 11, in <module>
import numpy.core.numeric as _nx
File
"/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/core/__init__.py",
line 14, in <module>
from . import multiarray
ImportError:
/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/core/multiarray.so:
undefined symbol: PyUnicodeUCS2_AsUTF8String

~~~~


Regards,
Jerrin

--001a113d2e7273191705504c708f
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr"><div>I don&#39;t think the first option works for us as we=
 have some=C2=A0bind=C2=A0points and the container ignores them in the --co=
ntain=C2=A0switch. The --cleanenv=C2=A0is also not available in the server =
version of singularity and my guess is would result in something similar.=
=C2=A0<br></div><div><br></div><div>I did not understand the second option.=
</div><div><br></div><div>The third option is the funny part, copied below =
is the result.</div><div><br></div><div>~~~~</div><div>S<font size=3D"1">in=
gularity.tensorflow.img&gt; which python <br>/N/soft/cle4/python/2.7.8/bin/=
python<br>Singularity.tensorflow.img&gt; python <br>Python 2.7.5 (default, =
Nov =C2=A06 2016, 00:28:07) <br>[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on =
linux2<br>Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot;=
 or &quot;license&quot; for more information.<br>Could not open PYTHONSTART=
UP<br>IOError: [Errno 2] No such file or directory: &#39;/etc/pythonstart&#=
39;<br>&gt;&gt;&gt; import numpy <br>Traceback (most recent call last):<br>=
File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;<br>File &quot;/N/=
soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/__init__.py&quot;,=
 line 180, in &lt;module&gt;<br>from . import add_newdocs<br>File &quot;/N/=
soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/add_newdocs.py&quo=
t;, line 13, in &lt;module&gt;<br>from numpy.lib import add_newdoc<br>File =
&quot;/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/lib/__ini=
t__.py&quot;, line 8, in &lt;module&gt;<br>from .type_check import *<br>Fil=
e &quot;/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/lib/typ=
e_check.py&quot;, line 11, in &lt;module&gt;<br>import numpy.core.numeric a=
s _nx<br>File &quot;/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/n=
umpy/core/__init__.py&quot;, line 14, in &lt;module&gt;<br>from . import mu=
ltiarray<br>ImportError: /N/soft/cle4/python/2.7.8/lib/python2.7/site-packa=
ges/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS2_AsUTF8String<=
/font><p class=3D"gmail-p1"><span class=3D"gmail-s1"><font size=3D"1">~~~~<=
/font></span></p><p class=3D"gmail-p1"><span class=3D"gmail-s1"><font size=
=3D"1"><br></font></span></p>Regards,<br>Jerrin</div></div>

--001a113d2e7273191705504c708f--
