X-Received: by 10.99.101.69 with SMTP id z66mr16624257pgb.161.1495651680978;
        Wed, 24 May 2017 11:48:00 -0700 (PDT)
X-BeenThere: singularity@lbl.gov
Received: by 10.36.107.87 with SMTP id v84ls2675650itc.12.gmail; Wed, 24 May
 2017 11:48:00 -0700 (PDT)
X-Received: by 10.99.133.194 with SMTP id u185mr41333495pgd.100.1495651679970;
        Wed, 24 May 2017 11:47:59 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1495651679; cv=none;
        d=google.com; s=arc-20160816;
        b=uTGrbwt3Q+fdNtJjXHhhIV1heuz41neH9RlJI7wHp58P3I3Gb62L2JuxGnVl80p80W
         MpFPP8wVNfY/vysSAXuym9sYfy45HE9+wZ25KQk14oSQ0IOWlGdJ1a28XjJOrXBUULkd
         DdtVdVXPgCuZX/MAqhKw8THe+mzXZH8A5XvKffd1JGLZmGTIhMoaA99HPjFfWQOU3X8q
         p0DXBMTcKGJGNEAGZgNvZvJqbluU3olzAoHK+eVtrTTBkZll9WgHAl6wrfdhDe1gEL26
         k3pRHlqZFKc62wsYvoC+Q/8nhkjDsudzHIWGCut4OL/uQcHwMri1i7OPEI8OLF14JpYg
         I1vA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=to:subject:message-id:date:from:mime-version:dkim-signature
         :arc-authentication-results;
        bh=CjDoLx5kSBl+Qk0t+Ld4qT+OiyuDOQpfW++xYZTxPRg=;
        b=Cbv2KuopYv2dcNPMbBzXB51Q2fiVcF/phjG5vaH3a367WO3x4WzRj8pLahJllkdLzS
         r8XkfhUfnnId7LGQa/up5oS6/FWg62jWeQxNZp2ft8Eung+gci/nyzGmb/F8ER71wEvV
         8vR2lEBhpmWWX/kt4vRdTzM1Y77HEql12O+6CXiKHs6WFVnpXtA7gj++KgY9OB0WKiMi
         J2WdT1JO2sLaQmJgqaamOxhXP1W07h5SJIeTvukPAEfasGQNC92jKaHHYQaZ54yH2MzQ
         04NicvJCkmrhGLdONsahyYdCd04X3ORsXMAG1N6l//pOMfgO1Y2hCkFSb0ewygtL6TKP
         VddA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass head...@gmail.com;
       spf=pass (google.com: domain of jerrin...@gmail.com designates 209.85.218.45 as permitted sender) smtp.mailfrom=jerrin...@gmail.com
Return-Path: <jerrin...@gmail.com>
Received: from fe3.lbl.gov (fe3.lbl.gov. [128.3.41.68])
        by mx.google.com with ESMTP id 139si25837466pgg.361.2017.05.24.11.47.59
        for <singu...@lbl.gov>;
        Wed, 24 May 2017 11:47:59 -0700 (PDT)
Received-SPF: pass (google.com: domain of jerrin...@gmail.com designates 209.85.218.45 as permitted sender) client-ip=209.85.218.45;
Authentication-Results: mx.google.com;
       dkim=pass head...@gmail.com;
       spf=pass (google.com: domain of jerrin...@gmail.com designates 209.85.218.45 as permitted sender) smtp.mailfrom=jerrin...@gmail.com
X-Ironport-SBRS: 2.7
X-IronPort-Anti-Spam-Filtered: true
X-IronPort-Anti-Spam-Result: =?us-ascii?q?A2HIBgDv1CVZfy3aVdFcHgYMGAEFAQsBg?=
 =?us-ascii?q?wFMAT6BDAeDaIE2my+IJIcphwRDLIFvhncHQxQBAQEBAQEBAQEBAQIQAQEJCws?=
 =?us-ascii?q?IJjGCMyIMBEYhCC4BAQEBAQEBAQEBAQEBAQEBARkCKwQIGQEbBCQdAQgTHgMSE?=
 =?us-ascii?q?DcCJAERAQUBiQuBNwEDDQgFCZ0xg0U/jAeBewkFARyDCgWDWwoZJw1WgyoqAgY?=
 =?us-ascii?q?Shk2BXoJognmFMYJgBYlAiESMH4FbhUWMCIJbjxyLWYRDgmoUH4EVNmFLLyAid?=
 =?us-ascii?q?IRPgiokNolCAQEB?=
X-IronPort-AV: E=Sophos;i="5.38,387,1491289200"; 
   d="scan'208,217";a="76178362"
Received: from mail-oi0-f45.google.com ([209.85.218.45])
  by fe3.lbl.gov with ESMTP; 24 May 2017 11:47:57 -0700
Received: by mail-oi0-f45.google.com with SMTP id h4so253303259oib.3
        for <singu...@lbl.gov>; Wed, 24 May 2017 11:47:57 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:from:date:message-id:subject:to;
        bh=CjDoLx5kSBl+Qk0t+Ld4qT+OiyuDOQpfW++xYZTxPRg=;
        b=tpXlJ3xAg2EpLg3ZebS/1UV+3tDDAsTplIG4bGhNugENJQSD+SikAlsIWUGhWM6ZSV
         tJbIewWVGEQDm8xTKPk37FxNxODX2qYlmHORgAW7ZN6tC87XVeb+ePB4PPK93Ju9TCDl
         DKpEGWlNLowrX1F6uPddvWP5E71DO7ahIl/Tw5cQ0+4srQo80+VHIkNaNuuVbqeBPlv8
         PuSTPnLNXFxx+7j+S7mUMurXUKl7n6bEj+tP4HOYd6e2OO/6HFChdgR+fGhxIBqkVoTg
         cualO0A1STtYNp44fNiWFjQycTV/iXQoo1bNAOHbEyhB/1l7FnN7TdlHo641Bo4wlEgZ
         8FFw==
X-Gm-Message-State: AODbwcCwk6CX2YU7cjuNuYuiVPERC7iGZK1FKJ5WRKEYm6On4JHvmIBP
	IB4C1WtfNkg72xH4ecAlQzJmquZcmJfqabM=
X-Received: by 10.157.56.151 with SMTP id p23mr5733004otc.239.1495651676846;
 Wed, 24 May 2017 11:47:56 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.157.17.106 with HTTP; Wed, 24 May 2017 11:47:36 -0700 (PDT)
From: Jerrin Suresh <jerrin...@gmail.com>
Date: Wed, 24 May 2017 14:47:36 -0400
Message-ID: <CA+KhMPsyKRrwZNrH_eeZpLZ-EXRdHfKMzdpUFj--g14gUUxAqg@mail.gmail.com>
Subject: Conflicting modules b/w container and host
To: singularity@lbl.gov
Content-Type: multipart/alternative; boundary="001a11c04432e8135c0550498a4a"

--001a11c04432e8135c0550498a4a
Content-Type: text/plain; charset="UTF-8"

Hi,

I am facing a unique issue of conflicting python modules within the
container as well as the one in the host machine. We have python 2.7.5
installed within the container which has a numpy installation. Now if a
user loads the python module on our HPC which is 2.7.8 which too has a
numpy installation. The 'import numpy' fails within the container.

~~~~~~
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcurand.so locally
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tensorflow/__init__.py", line 23,
in <module>
    from tensorflow.python import *
  File "/usr/lib/python2.7/site-packages/tensorflow/python/__init__.py",
line 45, in <module>
    from tensorflow.python import pywrap_tensorflow
  File
"/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py",
line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File
"/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py",
line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: numpy.core.multiarray failed to import
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/__init__.py",
line 180, in <module>
    from . import add_newdocs
  File
"/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/add_newdocs.py",
line 13, in <module>
    from numpy.lib import add_newdoc
  File
"/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/lib/__init__.py",
line 8, in <module>
    from .type_check import *
  File
"/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/lib/type_check.py",
line 11, in <module>
    import numpy.core.numeric as _nx
  File
"/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/core/__init__.py",
line 14, in <module>
    from . import multiarray
ImportError:
/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/core/multiarray.so:
undefined symbol: PyUnicodeUCS2_AsUTF8String
>>>
~~~~~~

This is how it works, when the host python module is unloaded

~~~~~~
Singularity.tensorflow.img> python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Could not open PYTHONSTARTUP
IOError: [Errno 2] No such file or directory: '/etc/pythonstart'
>>> import numpy
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcurand.so locally
>>>
~~~~~~

Regards,
Jerrin

-- 
MS CS Fall-16
Indiana University
www.linkedin.com/in/jerrinsuresh

--001a11c04432e8135c0550498a4a
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hi,<div><br></div><div>I am facing a unique issue of confl=
icting python modules within the container as well as the one in the host m=
achine. We have python 2.7.5 installed within the container which has a num=
py=C2=A0installation. Now if a user loads the python module on our HPC whic=
h is 2.7.8 which too has a numpy=C2=A0installation. The &#39;import numpy&#=
39; fails within the container.</div><div><br></div><div>~~~~~~</div><div><=
div><font size=3D"1">&gt;&gt;&gt; import tensorflow as tf=C2=A0</font></div=
><div><font size=3D"1">I tensorflow/stream_executor/dso_loader.cc:105] succ=
essfully opened CUDA library libcublas.so locally</font></div><div><font si=
ze=3D"1">I tensorflow/stream_executor/dso_loader.cc:105] successfully opene=
d CUDA library libcudnn.so locally</font></div><div><font size=3D"1">I tens=
orflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library =
libcufft.so locally</font></div><div><font size=3D"1">I tensorflow/stream_e=
xecutor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 lo=
cally</font></div><div><font size=3D"1">I tensorflow/stream_executor/dso_lo=
ader.cc:105] successfully opened CUDA library libcurand.so locally</font></=
div><div><font size=3D"1">ImportError: numpy.core.multiarray failed to impo=
rt</font></div><div><font size=3D"1">Traceback (most recent call last):</fo=
nt></div><div><font size=3D"1">=C2=A0 File &quot;&lt;stdin&gt;&quot;, line =
1, in &lt;module&gt;</font></div><div><font size=3D"1">=C2=A0 File &quot;/u=
sr/lib/python2.7/site-packages/tensorflow/__init__.py&quot;, line 23, in &l=
t;module&gt;</font></div><div><font size=3D"1">=C2=A0 =C2=A0 from tensorflo=
w.python import *</font></div><div><font size=3D"1">=C2=A0 File &quot;/usr/=
lib/python2.7/site-packages/tensorflow/python/__init__.py&quot;, line 45, i=
n &lt;module&gt;</font></div><div><font size=3D"1">=C2=A0 =C2=A0 from tenso=
rflow.python import pywrap_tensorflow</font></div><div><font size=3D"1">=C2=
=A0 File &quot;/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_te=
nsorflow.py&quot;, line 28, in &lt;module&gt;</font></div><div><font size=
=3D"1">=C2=A0 =C2=A0 _pywrap_tensorflow =3D swig_import_helper()</font></di=
v><div><font size=3D"1">=C2=A0 File &quot;/usr/lib/python2.7/site-packages/=
tensorflow/python/pywrap_tensorflow.py&quot;, line 24, in swig_import_helpe=
r</font></div><div><font size=3D"1">=C2=A0 =C2=A0 _mod =3D imp.load_module(=
&#39;_pywrap_tensorflow&#39;, fp, pathname, description)</font></div><div><=
font size=3D"1">ImportError: numpy.core.multiarray failed to import</font><=
/div><div><font size=3D"1">&gt;&gt;&gt; import numpy=C2=A0</font></div><div=
><font size=3D"1">Traceback (most recent call last):</font></div><div><font=
 size=3D"1">=C2=A0 File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt=
;</font></div><div><font size=3D"1">=C2=A0 File &quot;/N/soft/cle4/python/2=
.7.8/lib/python2.7/site-packages/numpy/__init__.py&quot;, line 180, in &lt;=
module&gt;</font></div><div><font size=3D"1">=C2=A0 =C2=A0 from . import ad=
d_newdocs</font></div><div><font size=3D"1">=C2=A0 File &quot;/N/soft/cle4/=
python/2.7.8/lib/python2.7/site-packages/numpy/add_newdocs.py&quot;, line 1=
3, in &lt;module&gt;</font></div><div><font size=3D"1">=C2=A0 =C2=A0 from n=
umpy.lib import add_newdoc</font></div><div><font size=3D"1">=C2=A0 File &q=
uot;/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/lib/__init_=
_.py&quot;, line 8, in &lt;module&gt;</font></div><div><font size=3D"1">=C2=
=A0 =C2=A0 from .type_check import *</font></div><div><font size=3D"1">=C2=
=A0 File &quot;/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/=
lib/type_check.py&quot;, line 11, in &lt;module&gt;</font></div><div><font =
size=3D"1">=C2=A0 =C2=A0 import numpy.core.numeric as _nx</font></div><div>=
<font size=3D"1">=C2=A0 File &quot;/N/soft/cle4/python/2.7.8/lib/python2.7/=
site-packages/numpy/core/__init__.py&quot;, line 14, in &lt;module&gt;</fon=
t></div><div><font size=3D"1">=C2=A0 =C2=A0 from . import multiarray</font>=
</div><div><font size=3D"1">ImportError: /N/soft/cle4/python/2.7.8/lib/pyth=
on2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUC=
S2_AsUTF8String</font></div><div><font size=3D"1">&gt;&gt;&gt;=C2=A0</font>=
</div></div><div>~~~~~~</div><div><br></div><div>This is how it works, when=
 the host python module is unloaded<br></div><div><br></div><div>~~~~~~</di=
v><div><div><font size=3D"1">Singularity.tensorflow.img&gt; python=C2=A0</f=
ont></div><div><font size=3D"1">Python 2.7.5 (default, Nov =C2=A06 2016, 00=
:28:07)=C2=A0</font></div><div><font size=3D"1">[GCC 4.8.5 20150623 (Red Ha=
t 4.8.5-11)] on linux2</font></div><div><font size=3D"1">Type &quot;help&qu=
ot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for =
more information.</font></div><div><font size=3D"1">Could not open PYTHONST=
ARTUP</font></div><div><font size=3D"1">IOError: [Errno 2] No such file or =
directory: &#39;/etc/pythonstart&#39;</font></div><div><font size=3D"1">&gt=
;&gt;&gt; import numpy=C2=A0</font></div><div><font size=3D"1">&gt;&gt;&gt;=
 import tensorflow as tf</font></div><div><font size=3D"1">I tensorflow/str=
eam_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.=
so locally</font></div><div><font size=3D"1">I tensorflow/stream_executor/d=
so_loader.cc:105] successfully opened CUDA library libcudnn.so locally</fon=
t></div><div><font size=3D"1">I tensorflow/stream_executor/dso_loader.cc:10=
5] successfully opened CUDA library libcufft.so locally</font></div><div><f=
ont size=3D"1">I tensorflow/stream_executor/dso_loader.cc:105] successfully=
 opened CUDA library libcuda.so.1 locally</font></div><div><font size=3D"1"=
>I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA l=
ibrary libcurand.so locally</font></div><div><font size=3D"1">&gt;&gt;&gt;=
=C2=A0</font></div><div>~~~~~~</div><div><br></div><div>Regards,</div><div>=
Jerrin</div><div><br></div>-- <br><div class=3D"gmail_signature"><div dir=
=3D"ltr"><div><div dir=3D"ltr"><div><div>MS CS Fall-16<br></div><div>Indian=
a University<br><span><span><a href=3D"http://www.linkedin.com/in/" target=
=3D"_blank">www.linkedin.com/in/</a></span><span>jerrinsuresh</span></span>=
<br></div><div dir=3D"ltr"><div><div><br></div></div></div></div></div></di=
v></div></div>
</div></div>

--001a11c04432e8135c0550498a4a--
